language: python

python:
  - "2.7"

script: 
  - python cx.py $Server $CxUsername $CxPassword $ClientSecret $ProjectName $TeamName $PresetName $FolderExclusions $FileExclusions https://bitbucket.org/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG.git "master" $HighThreshold $MediumThreshold $LowThreshold 