pipeline:
  identifier: Build_AST_OpenRoom_1691084546205
  name: Build AST_OpenRoom
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: Checkmarx One
        identifier: Checkmarx_One
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: JenkinsBuild
                  name: JenkinsBuild_1
                  identifier: JenkinsBuild_1
                  spec:
                    connectorRef: Jenkins
                    jobName: AST_BookStore
                    jobParameter: []
                    unstableStatusAsSuccess: false
                    useConnectorUrlForJobExecution: true
                  timeout: 1h
        tags: {}
