pipeline:
  identifier: Build_AST_OpenRoom_1691084546205
  name: Build AST_OpenRoom
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: CxOne DAST
        identifier: CxOne_DAST
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Container
                  name: Container_1
                  identifier: Container_1
                  spec:
                    connectorRef: Docker_Hub
                    image: checkmarx/dast
                    command: |
                      -e CX_APIKEY=$API_MASTER_KEY \
                        -v $(pwd):/demo checkmarx/dast:1.0.4 \
                        web \
                        --environment-id=b274d1e8-6cbf-4bff-b569-710cfcb8095f \
                        --config=/demo/config_sweet.yaml \
                        --base-url=https://ast.checkmarx.net \
                        --output=/demo/output \
                        --timeout=10000 \
                        --update-interval=10 \
                        --jvm-properties=-Xmx3G \
                        --log-level=info \
                        --verbose \
                        --retry=3 \
                        --retry-delay=20 \
                        --fail-on HIGH
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: MyConnector
                        namespace: checkmarx
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    outputVariables: []
                    envVariables:
                      API_MASTER_KEY: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2NjA0ZWY0Yy04NTcwLTRlOWYtOTM3Yy1hYTExM2RjM2ZhNjAifQ.eyJpYXQiOjE2NjY4MzM0NDksImp0aSI6ImQ1OGY0ZjE2LWJkOTUtNDZkNy04OGY2LTQ3ODY0NTliZDZhMCIsImlzcyI6Imh0dHBzOi8vaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvbGF0YW0iLCJhdWQiOiJodHRwczovL2lhbS5jaGVja21hcngubmV0L2F1dGgvcmVhbG1zL2xhdGFtIiwic3ViIjoiOTRmZTMwNjgtMmEyMi00ZGZhLWFjMzgtMDhjY2UwZTY5MGZkIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImFzdC1hcHAiLCJzZXNzaW9uX3N0YXRlIjoiNTkzMGM4ZjMtNmVjNy00NWMwLWJkYWItYjk1NjAyY2JmNmJkIiwic2NvcGUiOiIgb2ZmbGluZV9hY2Nlc3MiLCJzaWQiOiI1OTMwYzhmMy02ZWM3LTQ1YzAtYmRhYi1iOTU2MDJjYmY2YmQifQ.k5TwYpC17tw4G6Zj2zFBXRE82CybG5Cr_2LOIEXD27M
                  timeout: 30m
        tags: {}
    - stage:
        name: Checkmarx One
        identifier: Checkmarx_One
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_CxOne
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: false
                    source:
                      type: Inline
                      spec:
                        script: |-
                          wget -O cxcli.gz https://github.com/Checkmarx/ast-cli/releases/download/2.0.53/ast-cli_linux_x64.tar.gz
                          gunzip -f cxcli.gz
                          tar xvf cxcli
                          chmod +x cx
                          rm -rf src
                          mkdir src 
                          git clone https://github.com/cxronen/AST_OpenRoomProd.git src
                          ./apikey
                          ./cx scan create --project-name myproject -s /home/ubuntu/harness/src --branch main
                    environmentVariables: []
                    outputVariables: []
                    executionTarget:
                      connectorRef: Container_host_SSH
                      host: 192.168.56.125
                      workingDirectory: /home/ubuntu/harness
                  timeout: 10m
              - step:
                  type: JenkinsBuild
                  name: JenkinsBuild_1
                  identifier: JenkinsBuild_1
                  spec:
                    connectorRef: Jenkins
                    jobName: AST_BookStore
                    jobParameter: []
                    unstableStatusAsSuccess: false
                    useConnectorUrlForJobExecution: true
                  timeout: 1h
        tags: {}
